# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            polybits
tagline:          'Software and stuff'
description:      'A personal blog for yet another software engineer.'
url:              http://polybits.net/

author:
  name:           'Joseph Crail'
  url:            https://twitter.com/jbcrail

paginate:         5

# Custom vars
twitter:          https://twitter.com/jbcrail
github:           https://github.com/jbcrail
